version: '3.8'

services:
  mySQL:
    image: mysql:latest
    restart: always
    container_name: sqldb
    environment:
      - MYSQL_DATABASE=sqldb
      - MYSQL_ROOT_PASSWORD=dreamsql
    ports:
      - '3306:3306'
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      